# Generated by Django 4.1.2 on 2022-10-31 11:36

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_image_alter_article_description1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathegorie',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
    ]
