# Generated by Django 4.1.2 on 2022-10-31 12:18

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_cathegorie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=django_quill.fields.QuillField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='cathegorie',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
