# Generated by Django 4.1.2 on 2022-10-31 12:27

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_contenu_alter_cathegorie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=django_quill.fields.QuillField(),
        ),
    ]
