# Generated by Django 4.1.3 on 2022-12-01 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_contenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='liste',
            field=models.CharField(default=datetime.datetime(2022, 12, 1, 10, 20, 28, 448680, tzinfo=datetime.timezone.utc), max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='blog/videos'),
        ),
    ]
